FROM nginx:alpine-slim

LABEL org.opencontainers.image.source="https://github.com/cssnr/tibs3dprints-web"
LABEL org.opencontainers.image.description="Django 5 Boiler Plate"
LABEL org.opencontainers.image.authors="smashedr"

ENV TZ=UTC

COPY nginx.conf /etc/nginx/nginx.conf
