# Generated by Django 5.1.6 on 2025-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TikTokUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("open_id", models.CharField(blank=True, max_length=255)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                ("expires_in", models.DateTimeField(null=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("avatar_url", models.URLField(blank=True, max_length=510)),
            ],
            options={
                "verbose_name": "TikTok User",
                "verbose_name_plural": "TikTok Users",
            },
        ),
    ]
