# Generated by Django 5.1.6 on 2025-06-13 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail Address")),
                ("subject", models.CharField(max_length=128, verbose_name="Subject")),
                ("message", models.TextField(default=False, verbose_name="Message")),
                ("send_copy", models.BooleanField(verbose_name="Send Copy")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="UUID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.CreateModel(
            name="MyNews",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="The Title of the post.", max_length=64, verbose_name="Title")),
                (
                    "display_name",
                    models.CharField(
                        help_text="This should be your primary alias.", max_length=32, verbose_name="Display Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The entire body and full text of the post. Newlines are allowed.",
                        verbose_name="Description Body",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="The post will not show up unless this is checked.",
                        verbose_name="Published",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "My News",
                "verbose_name_plural": "My News",
                "ordering": ["-pk"],
            },
        ),
    ]
