# Generated by Django 5.1.6 on 2025-06-14 21:33

import django.db.models.deletion
import project.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BetaUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-Mail")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("details", models.TextField(blank=True, verbose_name="Details")),
                ("added", models.BooleanField(default=False, verbose_name="Added")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Beta User",
                "verbose_name_plural": "Beta Users",
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("question", models.TextField(verbose_name="Question")),
                ("start_at", models.DateTimeField(verbose_name="Start Date")),
                ("end_at", models.DateTimeField(verbose_name="End Date")),
                ("duration", models.IntegerField(default=72, verbose_name="Duration")),
            ],
            options={
                "verbose_name": "Poll",
                "verbose_name_plural": "Polls",
            },
        ),
        migrations.CreateModel(
            name="TikTokUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("authorization", models.CharField(default=project.helpers.get_rand, max_length=30)),
                ("open_id", models.CharField(blank=True, max_length=255)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                ("expires_in", models.DateTimeField(null=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("avatar_url", models.URLField(blank=True, max_length=510)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "TikTok User",
                "verbose_name_plural": "TikTok Users",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("file", models.FileField(upload_to=".", verbose_name="Image")),
                ("votes", models.IntegerField(default=0, verbose_name="Votes")),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.poll")),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notify_on_result", models.BooleanField(default=False)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                ("choice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.choice")),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.poll")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.tiktokuser")),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "unique_together": {("user", "poll")},
            },
        ),
    ]
