# Generated by Django 5.1.6 on 2025-06-28 00:33

import django.db.models.deletion
import project.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(blank=True, max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("verified", models.BooleanField(default=False)),
                ("authorization", models.CharField(default=project.helpers.gen_auth, max_length=255)),
                ("password", models.CharField(blank=True, editable=False, max_length=255)),
                ("points", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "App User",
                "verbose_name_plural": "App Users",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="BetaUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-Mail")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("details", models.TextField(blank=True, verbose_name="Details")),
                ("added", models.BooleanField(default=False, verbose_name="Added")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Beta User",
                "verbose_name_plural": "Beta Users",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("start_at", models.DateTimeField(verbose_name="Start Date")),
                ("end_at", models.DateTimeField(verbose_name="End Date")),
            ],
            options={
                "verbose_name": "Poll",
                "verbose_name_plural": "Polls",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.IntegerField(default=0)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.appuser")),
            ],
            options={
                "verbose_name": "Point",
                "verbose_name_plural": "Points",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("file", models.FileField(upload_to="choice/%Y/%m/", verbose_name="Image")),
                ("votes", models.IntegerField(default=0, verbose_name="Votes")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.poll")),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notify_on_result", models.BooleanField(default=False)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                ("choice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.choice")),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.poll")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.appuser")),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "ordering": ["-id"],
                "unique_together": {("user", "poll")},
            },
        ),
    ]
