# Generated by Django 5.1.6 on 2025-06-16 05:02

import project.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="betauser",
            options={"ordering": ["-id"], "verbose_name": "Beta User", "verbose_name_plural": "Beta Users"},
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["-id"], "verbose_name": "Choice", "verbose_name_plural": "Choices"},
        ),
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-id"], "verbose_name": "Poll", "verbose_name_plural": "Polls"},
        ),
        migrations.AlterModelOptions(
            name="tiktokuser",
            options={"ordering": ["-id"], "verbose_name": "TikTok User", "verbose_name_plural": "TikTok Users"},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"ordering": ["-id"], "verbose_name": "Vote", "verbose_name_plural": "Votes"},
        ),
        migrations.RemoveField(
            model_name="poll",
            name="duration",
        ),
        migrations.AddField(
            model_name="tiktokuser",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tiktokuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tiktokuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tiktokuser",
            name="authorization",
            field=models.CharField(default=project.helpers.gen_auth, max_length=255),
        ),
    ]
