# Generated by Django 5.1.6 on 2025-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
