# Generated by Django 5.1.6 on 2025-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_betauser_options_alter_choice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiktokuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="choice",
            name="file",
            field=models.FileField(upload_to="choice/%Y/%m/", verbose_name="Image"),
        ),
    ]
