# Generated by Django 5.1.6 on 2025-06-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_betauser_options_alter_choice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiktokuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
