version: "3"

services:
  app:
    build:
      context: ./app
      x-bake:
        platforms: [linux/amd64, linux/arm64]
        output: type=image,push=true
    image: ghcr.io/cssnr/tibs3dprints-web-app:latest

  nginx:
    build:
      context: ./nginx
      x-bake:
        platforms: [linux/amd64, linux/arm64]
        output: type=image,push=true
    image: ghcr.io/cssnr/tibs3dprints-web-nginx:latest
